GRANT USAGE ON WAREHOUSE SUPPLY_CHAIN_WH TO ROLE ENGINEER_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE ENGINEER_ROLE;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.BRONZE TO ROLE ENGINEER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.SILVER TO ROLE ENGINEER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES 
    IN SCHEMA SUPPLY_CHAIN_DB.BRONZE TO ROLE ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES 
    IN SCHEMA SUPPLY_CHAIN_DB.SILVER TO ROLE ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES 
    IN SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ENGINEER_ROLE;

GRANT SELECT ON ALL VIEWS 
    IN SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ENGINEER_ROLE;

SHOW GRANTS TO ROLE ENGINEER_ROLE;


GRANT USAGE ON WAREHOUSE SUPPLY_CHAIN_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ANALYST_ROLE;

GRANT SELECT ON ALL TABLES 
    IN SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS 
    IN SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE ANALYST_ROLE;

SHOW GRANTS TO ROLE ANALYST_ROLE;


GRANT USAGE ON WAREHOUSE SUPPLY_CHAIN_WH TO ROLE VIEWER_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_DB TO ROLE VIEWER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE VIEWER_ROLE;

GRANT SELECT ON ALL VIEWS 
    IN SCHEMA SUPPLY_CHAIN_DB.GOLD TO ROLE VIEWER_ROLE;

SHOW GRANTS TO ROLE VIEWER_ROLE;
