CREATE OR REPLACE VIEW GOLD.VW_KPI_SUMMARY AS
SELECT
    COUNT(ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(TOTAL_ORDER_VALUE), 2) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
    ROUND(SUM(CASE WHEN DELIVERY_PERFORMANCE = 'on time'
        THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS PCT_ON_TIME,
    ROUND(SUM(CASE WHEN DELIVERY_PERFORMANCE = 'delayed'
        THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS PCT_DELAYED,
    ROUND(MAX(SHIPPING_CHARGES), 2) AS MAX_SHIPPING
FROM SILVER.ORDERS;

SELECT * FROM GOLD.VW_KPI_SUMMARY;
