CREATE OR REPLACE VIEW GOLD.VW_MONTHLY_REVENUE AS
SELECT
    YEAR(ORDER_PURCHASE) AS ORDER_YEAR,
    MONTH(ORDER_PURCHASE) AS ORDER_MONTH,
    MONTHNAME(ORDER_PURCHASE) AS ORDER_MONTH_NAME,
    ROUND(SUM(TOTAL_ORDER_VALUE), 2) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
    COUNT(*) AS TOTAL_ORDERS
FROM SILVER.ORDERS
GROUP BY 1, 2, 3
ORDER BY 1, 2;

SELECT * FROM GOLD.VW_MONTHLY_REVENUE;
