CREATE OR REPLACE VIEW GOLD.VW_MONTHLY_DELAY_RATE AS
SELECT
    YEAR(ORDER_PURCHASE) AS ORDER_YEAR,
    MONTH(ORDER_PURCHASE) AS ORDER_MONTH,
    MONTHNAME(ORDER_PURCHASE) AS ORDER_MONTH_NAME,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(CASE WHEN DELIVERY_PERFORMANCE = 'delayed'
        THEN 1 ELSE 0 END) AS DELAYED_ORDERS,
    ROUND(SUM(CASE WHEN DELIVERY_PERFORMANCE = 'delayed'
        THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS PCT_DELAYED
FROM SILVER.ORDERS
GROUP BY 1, 2, 3
ORDER BY 1, 2;

SELECT * FROM GOLD.VW_MONTHLY_DELAY_RATE;
