CREATE OR REPLACE VIEW GOLD.VW_WORST_CITY AS
SELECT
    c.CUSTOMER_CITY,
    COUNT(*) AS DELAYED_ORDERS
FROM SILVER.ORDERS o
JOIN SILVER.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.DELIVERY_PERFORMANCE = 'delayed'
GROUP BY 1
ORDER BY DELAYED_ORDERS DESC
LIMIT 1;

SELECT * FROM GOLD.VW_WORST_CITY;