CREATE OR REPLACE VIEW GOLD.VW_WORST_CATEGORY AS
SELECT
    p.PRODUCT_CATEGORY,
    COUNT(*) AS DELAYED_ORDERS
FROM SILVER.ORDERS o
JOIN SILVER.PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.DELIVERY_PERFORMANCE = 'delayed'
AND p.PRODUCT_CATEGORY IS NOT NULL
GROUP BY 1
ORDER BY DELAYED_ORDERS DESC
LIMIT 1;

SELECT * FROM GOLD.VW_WORST_CATEGORY;
