CREATE OR REPLACE VIEW GOLD.VW_TOP10_CITIES_DELAY AS
SELECT
    c.CUSTOMER_CITY,
    ROUND(AVG(o.ORDER_PERFORMANCE_DAYS), 1) AS AVG_DELIVERY_DAYS,
    COUNT(*) AS TOTAL_ORDERS
FROM SILVER.ORDERS o
JOIN SILVER.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.ORDER_DELIVERED IS NOT NULL
GROUP BY 1
ORDER BY AVG_DELIVERY_DAYS DESC
LIMIT 10;

SELECT * FROM GOLD.VW_TOP10_CITIES_DELAY;