CREATE OR REPLACE VIEW GOLD.VW_DELAYED_BY_CITY_MAP AS
SELECT
    c.CUSTOMER_CITY,
    c.CUSTOMER_STATE,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(CASE WHEN o.DELIVERY_PERFORMANCE = 'delayed'
        THEN 1 ELSE 0 END) AS DELAYED_ORDERS,
    ROUND(SUM(CASE WHEN o.DELIVERY_PERFORMANCE = 'delayed'
        THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS PCT_DELAYED
FROM SILVER.ORDERS o
JOIN SILVER.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY 1, 2
ORDER BY PCT_DELAYED DESC;

SELECT * FROM GOLD.VW_DELAYED_BY_CITY_MAP;
