CREATE OR REPLACE VIEW GOLD.VW_ORDER_DISTRIBUTION AS
SELECT
    DELIVERY_PERFORMANCE,
    COUNT(*) AS ORDER_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM SILVER.ORDERS
GROUP BY DELIVERY_PERFORMANCE;

SELECT * FROM GOLD.VW_ORDER_DISTRIBUTION;
