CREATE OR REPLACE VIEW GOLD.VW_SHIPPING_BY_PERFORMANCE AS
SELECT
    DELIVERY_PERFORMANCE,
    ROUND(MEDIAN(SHIPPING_CHARGES), 2) AS MEDIAN_SHIPPING,
    ROUND(AVG(SHIPPING_CHARGES), 2) AS AVG_SHIPPING,
    ROUND(MIN(SHIPPING_CHARGES), 2) AS MIN_SHIPPING,
    ROUND(MAX(SHIPPING_CHARGES), 2) AS MAX_SHIPPING,
    COUNT(*) AS TOTAL_ORDERS
FROM SILVER.ORDERS
GROUP BY 1;

SELECT * FROM GOLD.VW_SHIPPING_BY_PERFORMANCE;
