CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.GOLD.DIM_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_ZIP_CODE,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM SUPPLY_CHAIN_DB.SILVER.CUSTOMERS;

CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.GOLD.DIM_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_WEIGHT,
    PRODUCT_LENGTH,
    PRODUCT_HEIGHT,
    PRODUCT_WIDTH
FROM SUPPLY_CHAIN_DB.SILVER.PRODUCTS;

CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.GOLD.FACT_ORDERS AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.PRODUCT_ID,
    o.SELLER_ID,
    o.ORDER_STATUS,
    o.ORDER_PURCHASE,
    o.ORDER_APPROVED,
    o.ORDER_DELIVERED,
    o.ESTIMATED_DELIVERY,
    o.PRICE,
    o.SHIPPING_CHARGES,
    o.TOTAL_ORDER_VALUE,
    o.ORDER_PERFORMANCE_DAYS,
    o.DELIVERY_PERFORMANCE
FROM SUPPLY_CHAIN_DB.SILVER.ORDERS o;