ALTER TABLE SUPPLY_CHAIN_DB.SILVER.CUSTOMERS
RENAME COLUMN CUSTOMER_ZIP_CODE_PREFIX TO CUSTOMER_ZIP_CODE;


ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
RENAME COLUMN ORDER_PURCHASE_TIMESTAMP TO ORDER_PURCHASE;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
RENAME COLUMN ORDER_APPROVED_AT TO ORDER_APPROVED;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
RENAME COLUMN ORDER_DELIVERED_TIMESTAMP TO ORDER_DELIVERED;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
RENAME COLUMN ORDER_ESTIMATED_DELIVERY_DATE TO ESTIMATED_DELIVERY;


ALTER TABLE SUPPLY_CHAIN_DB.SILVER.PRODUCTS
RENAME COLUMN PRODUCT_CATEGORY_NAME TO PRODUCT_CATEGORY;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.PRODUCTS
RENAME COLUMN PRODUCT_WEIGHT_G TO PRODUCT_WEIGHT;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.PRODUCTS
RENAME COLUMN PRODUCT_LENGTH_CM TO PRODUCT_LENGTH;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.PRODUCTS
RENAME COLUMN PRODUCT_HEIGHT_CM TO PRODUCT_HEIGHT;

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.PRODUCTS
RENAME COLUMN PRODUCT_WIDTH_CM TO PRODUCT_WIDTH;
