ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
ALTER COLUMN PRICE SET DATA TYPE NUMBER(10,2);

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
ALTER COLUMN SHIPPING_CHARGES SET DATA TYPE NUMBER(10,2);

ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS
ALTER COLUMN SELLER_ID SET DATA TYPE VARCHAR(50);