ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN SELLER_ID VARCHAR(50);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN PRICE NUMBER(10,2);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN SHIPPING_CHARGES NUMBER(10,2);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN TOTAL_ORDER_VALUE NUMBER(10,2);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN PRODUCT_ID VARCHAR;
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN ESTIMATED_ORDER_PERFORMANCE_DAYS NUMBER(5,0);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN ORDER_PERFORMANCE_DAYS NUMBER(5,0);
ALTER TABLE SUPPLY_CHAIN_DB.SILVER.ORDERS ADD COLUMN DELIVERY_PERFORMANCE VARCHAR;