UPDATE SUPPLY_CHAIN_DB.SILVER.ORDERS o
SET o.SELLER_ID = oi.SELLER_ID,
    o.PRICE = oi.PRICE,
    o.SHIPPING_CHARGES = oi.SHIPPING_CHARGES,
    o.PRODUCT_ID = oi.PRODUCT_ID
FROM SUPPLY_CHAIN_DB.BRONZE.ORDER_ITEMS oi
WHERE o.ORDER_ID = oi.ORDER_ID;

UPDATE SUPPLY_CHAIN_DB.SILVER.ORDERS
SET TOTAL_ORDER_VALUE = PRICE + SHIPPING_CHARGES;

UPDATE SILVER.ORDERS
SET
    ORDER_PERFORMANCE_DAYS = DATEDIFF('day', ORDER_APPROVED, ORDER_DELIVERED),

    ESTIMATED_ORDER_PERFORMANCE_DAYS = DATEDIFF('day', ORDER_APPROVED, ESTIMATED_DELIVERY),

    DELIVERY_PERFORMANCE = CASE
        WHEN ORDER_APPROVED IS NULL OR ORDER_DELIVERED IS NULL  
            THEN 'unknown'
        WHEN DATEDIFF('day', ORDER_APPROVED, ORDER_DELIVERED) 
           < DATEDIFF('day', ORDER_APPROVED, ESTIMATED_DELIVERY)  
            THEN 'early'
        WHEN DATEDIFF('day', ORDER_APPROVED, ORDER_DELIVERED) 
           > DATEDIFF('day', ORDER_APPROVED, ESTIMATED_DELIVERY)  
            THEN 'delayed'
        WHEN DATEDIFF('day', ORDER_APPROVED, ORDER_DELIVERED) 
           = DATEDIFF('day', ORDER_APPROVED, ESTIMATED_DELIVERY)  
            THEN 'on time'
    END;
