CREATE TABLE IF NOT EXISTS SILVER.AUDIT_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCEDURE_NAME VARCHAR(100),
    STATUS VARCHAR(20),
    ROWS_PROCESSED NUMBER,
    MESSAGE VARCHAR(500)
);

SELECT * FROM SILVER.AUDIT_LOG ORDER BY LOG_TIMESTAMP DESC;
